name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: StuartYang/social-readme@master
        with:
          blog_rss_link: https://yangxudong.site/index.php/feed/
          douban_name: yang_xudong
